nodeLinker: node-modules

plugins:
  - path: homeassistant-frontend/.yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: homeassistant-frontend/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: homeassistant-frontend/.yarn/releases/yarn-3.2.0.cjs
