// Dependency rules. `dependencies`, `devDependencies` and `resolutions` in package.json are
// generated by script/merge_requirements.js from homeassistant-frontend/package.json with the KNX
// `*Override` maps on top, so anything else is silently undone by the next submodule upgrade.

import { builtinModules } from "node:module";
import { compareVersions } from "../../../merging-knx-frontend-dependabot-prs/scripts/lib/pr.mjs";
import { matchAdded } from "./diff.mjs";
import { finding } from "./findings.mjs";

const SECTIONS = [
  ["dependencies", "dependenciesOverride"],
  ["devDependencies", "devDependenciesOverride"],
  ["resolutions", "resolutionsOverride"],
];
const EVIDENCE = ["#99", "#232", "#461"];
const PLAIN_VERSION = /^\d+\.\d+\.\d+([-+].*)?$/;
const BUILTINS = new Set(builtinModules);

const toSubmodule = (value) => value.replace(/\.yarn\//g, "homeassistant-frontend/.yarn/");

export function mergeRequirements(knx, core) {
  const merged = { packageManager: core.packageManager };
  for (const [section, override] of SECTIONS) {
    const upstream = Object.entries(core[section] ?? {}).map(([name, value]) => [
      name,
      toSubmodule(value),
    ]);
    merged[section] = { ...Object.fromEntries(upstream), ...(knx[override] ?? {}) };
  }
  return merged;
}

export function keyLine(text, section, key) {
  const lines = text.split("\n");
  const start = lines.findIndex((line) => line.startsWith(`  "${section}": {`));
  if (start < 0) return null;
  for (let i = start + 1; i < lines.length && !/^ {2}\}/.test(lines[i]); i++) {
    if (lines[i].startsWith(`    "${key}":`)) return i + 1;
  }
  return start + 1;
}

export function mergeFindings(knx, core, text) {
  const expected = mergeRequirements(knx, core);
  const results = [];
  for (const [section, override] of SECTIONS) {
    const actual = knx[section] ?? {};
    const want = expected[section];
    for (const name of new Set([...Object.keys(actual), ...Object.keys(want)])) {
      if (actual[name] === want[name]) continue;
      let message;
      if (want[name] === undefined) {
        message = `${section}.${name} is neither upstream nor in ${override}; script/merge_requirements.js drops it on the next submodule upgrade. Add it to ${override} as well.`;
      } else if (actual[name] === undefined) {
        message = `${section}.${name} (${want[name]}) is missing; script/merge_requirements.js adds it back. Run node script/merge_requirements.js && yarn install.`;
      } else {
        message = `${section}.${name} is ${actual[name]}, but the merge gives ${want[name]}; the next upgrade reverts it. Change ${override} instead and re-run script/merge_requirements.js.`;
      }
      results.push(
        finding({
          rule: "DEP-merge",
          severity: "blocker",
          file: "package.json",
          line: keyLine(text, section, name),
          message,
          evidence: EVIDENCE,
          key: `${section}.${name}`,
        }),
      );
    }
  }
  if (knx.packageManager !== expected.packageManager) {
    results.push(
      finding({
        rule: "DEP-merge",
        severity: "blocker",
        file: "package.json",
        line: null,
        message: `packageManager is ${knx.packageManager}, the submodule has ${expected.packageManager}.`,
        evidence: EVIDENCE,
        key: "packageManager",
      }),
    );
  }
  return results;
}

export const packageOf = (specifier) =>
  specifier
    .split("/")
    .slice(0, specifier.startsWith("@") ? 2 : 1)
    .join("/");

const IMPORT = /(?:\bfrom|\bimport|\brequire)\s*\(?\s*["']([^"'\s]+)["']/g;
const IMPORTING_FILE = /^(src|build-scripts)\/.+\.(ts|js|mjs|cjs)$/;

export function importFindings(files, knx, core, srcEntries) {
  const known = new Set([
    ...Object.keys(core.dependencies ?? {}),
    ...Object.keys(core.devDependencies ?? {}),
    ...Object.keys(knx.dependenciesOverride ?? {}),
    ...Object.keys(knx.devDependenciesOverride ?? {}),
  ]);
  const results = [];
  for (const file of files) {
    if (file.status === "deleted" || !IMPORTING_FILE.test(file.path)) continue;
    const seen = new Set();
    for (const { match, line } of matchAdded(file, IMPORT)) {
      const specifier = match[1];
      if (/^[./]/.test(specifier) || specifier.startsWith("@ha/") || specifier.startsWith("node:"))
        continue;
      const name = packageOf(specifier);
      if (BUILTINS.has(name) || srcEntries.has(specifier.split("/")[0]) || known.has(name))
        continue;
      if (seen.has(name)) continue;
      seen.add(name);
      results.push(
        finding({
          rule: "DEP-import",
          severity: "blocker",
          file: file.path,
          line,
          message: `"${name}" is neither declared by homeassistant-frontend nor in a *Override; add it to dependenciesOverride (or devDependenciesOverride) and to dependencies.`,
          evidence: ["#440", "#461"],
        }),
      );
    }
  }
  return results;
}

// Only a change to what gets installed needs a new lockfile; scripts or metadata do not.
export function lockFindings(files, basePkg, headPkg) {
  const paths = new Set(files.map((file) => file.path));
  if (!paths.has("package.json") || paths.has("yarn.lock")) return [];
  const installed = (pkg) =>
    JSON.stringify(SECTIONS.map(([section]) => Object.entries(pkg?.[section] ?? {}).sort()));
  if (installed(basePkg) === installed(headPkg)) return [];
  return [
    finding({
      rule: "DEP-lock",
      severity: "should-fix",
      file: "package.json",
      line: null,
      message:
        "Dependencies in package.json changed but yarn.lock did not; run yarn install and yarn dedupe.",
    }),
  ];
}

export function staleOverrideFindings(packageFile, knx, core) {
  const results = new Map();
  for (const { line, text } of packageFile?.added ?? []) {
    const name = text.match(/^\s*"([^"]+)":\s*"/)?.[1];
    if (!name) continue;
    for (const [section, override] of SECTIONS) {
      const mine = knx[override]?.[name];
      const upstream = core[section]?.[name];
      if (!mine || !upstream || !PLAIN_VERSION.test(mine) || !PLAIN_VERSION.test(upstream))
        continue;
      if (compareVersions(mine, upstream) > 0 || results.has(`${override}.${name}`)) continue;
      results.set(
        `${override}.${name}`,
        finding({
          rule: "DEP-stale-override",
          severity: "nit",
          file: "package.json",
          line,
          message: `${override}.${name} is ${mine}, upstream already has ${upstream}; drop the override and re-run script/merge_requirements.js.`,
        }),
      );
    }
  }
  return [...results.values()];
}
