import fs from "fs";

const rawPackageCore = fs.readFileSync("./homeassistant-frontend/package.json");
const rawPackageKnx = fs.readFileSync("./package.json");

const packageCore = JSON.parse(rawPackageCore);
const packageKnx = JSON.parse(rawPackageKnx);

fs.writeFileSync(
  "./package.json",
  JSON.stringify(
    {
      ...packageKnx,
      dependencies: { ...packageCore.dependencies, ...packageKnx.dependenciesOverride },
      devDependencies: {
        ...packageCore.devDependencies,
        ...packageKnx.devDependenciesOverride,
      },
      packageManager: packageCore.packageManager,
    },
    null,
    2,
  ),
);

// pnpm settings (overrides, patched dependencies, supply-chain protection) live in
// pnpm-workspace.yaml. Reuse upstream's, pointing its patch files into the submodule.
const workspaceCore = fs.readFileSync("./homeassistant-frontend/pnpm-workspace.yaml", "utf8");
const workspaceKnx = workspaceCore.replace(/^(\s+\S+:\s*["']?)patches\//gm, "$1homeassistant-frontend/patches/");
fs.writeFileSync(
  "./pnpm-workspace.yaml",
  "# Generated by script/merge_requirements.js from homeassistant-frontend/pnpm-workspace.yaml.\n" +
    "# Do not edit manually, changes are overwritten on the next frontend upgrade.\n\n" +
    workspaceKnx,
);
