#!/bin/sh
# Resolve all frontend dependencies that the application requires to develop.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

cd homeassistant-frontend
git pull
rm -f yarn.lock
node ./script/merge_requirements.js