#!/bin/sh
# Resolve all frontend dependencies that the application requires to develop.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

echo "Updating frontend submodule"
cd homeassistant-frontend
git fetch --tags
latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
git checkout $latestTag
cd ..

# echo "Removing yarn.lock"
# rm -f yarn.lock

echo "Merging requirements"
node ./script/merge_requirements.js

echo "Installing modules"
yarn install
