name: "Release actions"

on:
  release:
    types: ["published"]

env:
  NODE_VERSION: 16
  PYTHON_VERSION: "3.x"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to PyPi
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: "Set version number from tag"
        run: |
          echo '${{ github.ref }}' > ./VERSION
          cat ./VERSION

      - name: Install dependencies
        run: |
          python -m pip install build twine
          ./script/bootstrap

      - name: Build
        run: yarn build

      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m build
          twine upload dist/*
